# Generated by Django 4.1.4 on 2023-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=100)),
                ('duresion', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('fee', models.IntegerField()),
                ('timeing', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
