# Generated by Django 4.1.4 on 2023-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='trainer_exp',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
