# Generated by Django 4.1.4 on 2023-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojectapp', '0002_courses_trainer_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateField(max_length=100)),
            ],
        ),
    ]
